### ISSUE TITLE
Crash when pressing ? from the adapters page

### ISSUE THREAD

**Issue by fritz47110815** [sbormann/ioBroker.iqontrol#248]
**Describe the bug**  
When ever I press the ? in the adapter's page of iqontrol a crash occur

**To Reproduce**  
1. open adapters
2. find iqontrol
3. press the 3 vertical dots
4. press ?

**Expected behavior**  
Display of the help page

**Screenshots & Logfiles**  
```
instrument.ts:124 Cannot semver: TypeError: Invalid Version: **WORK
(anonymous) @ instrument.ts:124
instrument.ts:124 maximum nesting of 10 spans reached!!!
(anonymous) @ instrument.ts:124
instrument.ts:124 Warning: Could not map element with type "directive". t
(anonymous) @ instrument.ts:124
instrument.ts:124 Warning: Could not map element with type "script". t
(anonymous) @ instrument.ts:124
instrument.ts:124 Warning: Could not map element with type "script". t
(anonymous) @ instrument.ts:124
6instrument.ts:124 Error: Minified React error #137; visit https://reactjs.org/docs/error-decoder.html?invariant=137&args[]=meta for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ee (react-dom.production.min.js:47:92)
    at ii (react-dom.production.min.js:208:42)
    at Ll (react-dom.production.min.js:251:81)
    at jl (react-dom.production.min.js:250:408)
    at Vl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at a.m.setState (react.production.min.js:12:369)
    at a.<anonymous> (AdapterInfoDialog.js:76:18)
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at i (asyncToGenerator.js:25:9)
(anonymous) @ instrument.ts:124
instrument.ts:124 Error: Minified React error #137; visit https://reactjs.org/docs/error-decoder.html?invariant=137&args[]=link for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ee (react-dom.production.min.js:47:92)
    at ii (react-dom.production.min.js:208:42)
    at Ll (react-dom.production.min.js:251:81)
    at jl (react-dom.production.min.js:250:408)
    at Vl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at a.m.setState (react.production.min.js:12:369)
    at a.<anonymous> (AdapterInfoDialog.js:76:18)
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at i (asyncToGenerator.js:25:9)
(anonymous) @ instrument.ts:124

```
**Versions:**  
 - Adapter version: 2.0.1
 - JS-Controller version: 4.0.23
 - Node version: v14.19.3
 - Operating system: Linux

**Additional context**

**Comment by fritz47110815** [comment]
![Bildschirmfoto 2022-05-20 um 22 58 24](https://user-images.githubusercontent.com/66571432/169609863-b13cd21d-de35-4a08-ab3a-01ef93c02282.png)
![Bildschirmfoto 2022-05-20 um 22 59 01](https://user-images.githubusercontent.com/66571432/169609882-e2e35088-176a-4123-a88a-72be81bd1569.png)
![Bildschirmfoto 2022-05-20 um 22 59 32](https://user-images.githubusercontent.com/66571432/169609893-5a043338-39d8-48ac-a97a-8fb9c24cb0e8.png)

**Comment by sbormann** [comment]
Wird in der nächsten Version behoben (kannst testweise mal die Github-Version installieren). Bluefox hat die Readme überarbeitet. Falls es weiter Probleme gibt, bitte noch mal melden. VG!
