### ISSUE TITLE
Iqontrol startet nicht mit der neuen Hostversion 5.0.2

### ISSUE THREAD

**Issue by AlfredSch** [sbormann/ioBroker.iqontrol#279]
Hallo zusammen
Mit der neuen Hostversion startet die Iqontrol Instanz nicht mehr. 
Gruss
Fred

2023-06-12 16:59:04.506 - warn: iqontrol.2 (3900) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-06-12 16:59:04.928 - info: host.Brocker instance system.adapter.web.0 started with pid 3915
2023-06-12 16:59:05.007 - info: iqontrol.2 (3900) terminating
2023-06-12 16:59:05.062 - error: host.Brocker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-06-12 16:59:05.062 - error: host.Brocker Caught by controller[0]: Error: Parameter "options" needs to be a real object but type "string" has been passed
2023-06-12 16:59:05.062 - error: host.Brocker Caught by controller[0]: at Function.assertObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:301:19)
2023-06-12 16:59:05.062 - error: host.Brocker Caught by controller[0]: at Iqontrol.getObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:3551:23)
2023-06-12 16:59:05.062 - error: host.Brocker Caught by controller[0]: at /opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2254:16
2023-06-12 16:59:05.062 - error: host.Brocker Caught by controller[0]: at new Promise ()
2023-06-12 16:59:05.062 - error: host.Brocker Caught by controller[0]: at Iqontrol.getObjectAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2253:16)
2023-06-12 16:59:05.062 - error: host.Brocker Caught by controller[0]: at Iqontrol.createOrUpdateObject (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1673:25)
2023-06-12 16:59:05.062 - error: host.Brocker Caught by controller[0]: at Iqontrol.createInfoConnection (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:413:14)
2023-06-12 16:59:05.062 - error: host.Brocker Caught by controller[0]: at Iqontrol.onReady (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1779:14)
2023-06-12 16:59:05.062 - error: host.Brocker Caught by controller[0]: at Iqontrol.emit (node:events:513:28)
2023-06-12 16:59:05.062 - error: host.Brocker Caught by controller[0]: at Iqontrol.emit (node:domain:489:12)
2023-06-12 16:59:05.062 - error: host.Brocker instance system.adapter.iqontrol.2 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-06-12 16:59:05.062 - info: host.Brocker Restart adapter system.adapter.iqontrol.2 because enabled
2023-06-12 16:59:05.365 - info: web.0 (3915) starting. Version 5.5.3 in /opt/iobroker/node_modules/iobroker.web, node: v18.16.0, js-controller: 5.0.2

**Comment by sbormann** [comment]
Hi, maybe it is the same as mentioned here #276   
Could you please try the actual github version?

**Comment by vepman** [comment]
Hallo, 
bei mir läuft iqontrol mit js-controller5.02 auch nicht mehr.
Die aktuelle Github-Version ist seit gerade installiert.
Hardware: Proxmox Container mit iobroker Beta repository


`host.iobroker | 2023-06-13 10:01:22.504 | error | instance system.adapter.iqontrol.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
host.iobroker | 2023-06-13 10:01:22.504 | error | Caught by controller[1]: at Iqontrol.emit (node:domain:489:12)
host.iobroker | 2023-06-13 10:01:22.504 | error | Caught by controller[1]: at Iqontrol.emit (node:events:513:28)
host.iobroker | 2023-06-13 10:01:22.504 | error | Caught by controller[1]: at Iqontrol.onReady (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1779:14)
host.iobroker | 2023-06-13 10:01:22.504 | error | Caught by controller[1]: at Iqontrol.createInfoConnection (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:413:14)
host.iobroker | 2023-06-13 10:01:22.504 | error | Caught by controller[1]: at Iqontrol.createOrUpdateObject (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1673:25)
host.iobroker | 2023-06-13 10:01:22.504 | error | Caught by controller[1]: at Iqontrol.getObjectAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2253:16)
host.iobroker | 2023-06-13 10:01:22.504 | error | Caught by controller[1]: at new Promise (<anonymous>)
host.iobroker | 2023-06-13 10:01:22.504 | error | Caught by controller[1]: at /opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2254:16
host.iobroker | 2023-06-13 10:01:22.504 | error | Caught by controller[1]: at Iqontrol.getObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:3551:23)
host.iobroker | 2023-06-13 10:01:22.504 | error | Caught by controller[1]: at Function.assertObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:301:19)
host.iobroker | 2023-06-13 10:01:22.504 | error | Caught by controller[1]: Error: Parameter "options" needs to be a real object but type "string" has been passed
host.iobroker | 2023-06-13 10:01:22.504 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:`

**Comment by OstfrieseUnterwegs** [comment]
Versionen: 
Controller: 5.0.3
iqontrol: von git die aktuelle geladen

Prinzipiell läuft iqontrol, aber nach Start und bei Save kommt sowas:

```

2023-06-14 13:44:37.880 - error: iqontrol.0 (133739) ERROR updating object: info.connection: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.929 - error: iqontrol.0 (133739) ERROR updating object: passphrase: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.931 - error: iqontrol.0 (133739) ERROR updating object: Popup.Message: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.931 - error: iqontrol.0 (133739) ERROR updating object: Popup.PersistentMessage: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.932 - error: iqontrol.0 (133739) ERROR updating object: Popup.PersistentExpires: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.933 - error: iqontrol.0 (133739) ERROR updating object: Popup.PersistentUndismissible: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.934 - error: iqontrol.0 (133739) ERROR updating object: Popup.PersistentId: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.935 - error: iqontrol.0 (133739) ERROR updating object: Popup.PERSISTENT_MESSAGES_DELETE_ID: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.935 - error: iqontrol.0 (133739) ERROR updating object: Popup.PERSISTENT_MESSAGES_SHOW_ID: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.936 - error: iqontrol.0 (133739) ERROR updating object: Popup.PERSISTENT_MESSAGES_PENDING: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.937 - error: iqontrol.0 (133739) ERROR updating object: Popup.Duration: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.938 - error: iqontrol.0 (133739) ERROR updating object: Popup.ClickKeepsOpen: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.939 - error: iqontrol.0 (133739) ERROR updating object: Popup.ClickedValue: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.940 - error: iqontrol.0 (133739) ERROR updating object: Popup.ClickedDestinationState: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.940 - error: iqontrol.0 (133739) ERROR updating object: Popup.POPUP_CLICKED: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.941 - error: iqontrol.0 (133739) ERROR updating object: Popup.ButtonNames: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.942 - error: iqontrol.0 (133739) ERROR updating object: Popup.ButtonValues: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.943 - error: iqontrol.0 (133739) ERROR updating object: Popup.ButtonDestinationStates: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.943 - error: iqontrol.0 (133739) ERROR updating object: Popup.ButtonCloses: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.944 - error: iqontrol.0 (133739) ERROR updating object: Popup.ButtonClears: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.945 - error: iqontrol.0 (133739) ERROR updating object: Popup.BUTTON_CLICKED: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:37.945 - error: iqontrol.0 (133739) ERROR updating object: Popup.CLEAR: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:38.309 - error: iqontrol.0 (133739) ERROR updating object: Lists.Lichter.TOTAL: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:38.310 - error: iqontrol.0 (133739) ERROR updating object: Lists.Lichter.TOTAL_LIST: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:38.311 - error: iqontrol.0 (133739) ERROR updating object: Lists.Lichter.TOTAL_LIST_JSON: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:38.311 - error: iqontrol.0 (133739) ERROR updating object: Lists.Lichter.An: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:38.312 - error: iqontrol.0 (133739) ERROR updating object: Lists.Lichter.An_LIST: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:38.312 - error: iqontrol.0 (133739) ERROR updating object: Lists.Lichter.An_LIST_JSON: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.221 - error: iqontrol.0 (133850) ERROR updating object: info.connection: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.269 - error: iqontrol.0 (133850) ERROR updating object: passphrase: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.297 - error: iqontrol.0 (133850) ERROR updating object: Popup.Message: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.299 - error: iqontrol.0 (133850) ERROR updating object: Popup.PersistentMessage: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.300 - error: iqontrol.0 (133850) ERROR updating object: Popup.PersistentExpires: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.311 - error: iqontrol.0 (133850) ERROR updating object: Popup.PersistentUndismissible: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.313 - error: iqontrol.0 (133850) ERROR updating object: Popup.PersistentId: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.314 - error: iqontrol.0 (133850) ERROR updating object: Popup.PERSISTENT_MESSAGES_DELETE_ID: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.316 - error: iqontrol.0 (133850) ERROR updating object: Popup.PERSISTENT_MESSAGES_SHOW_ID: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.317 - error: iqontrol.0 (133850) ERROR updating object: Popup.PERSISTENT_MESSAGES_PENDING: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.318 - error: iqontrol.0 (133850) ERROR updating object: Popup.Duration: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.320 - error: iqontrol.0 (133850) ERROR updating object: Popup.ClickKeepsOpen: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.321 - error: iqontrol.0 (133850) ERROR updating object: Popup.ClickedValue: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.322 - error: iqontrol.0 (133850) ERROR updating object: Popup.ClickedDestinationState: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.323 - error: iqontrol.0 (133850) ERROR updating object: Popup.POPUP_CLICKED: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.324 - error: iqontrol.0 (133850) ERROR updating object: Popup.ButtonNames: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.325 - error: iqontrol.0 (133850) ERROR updating object: Popup.ButtonValues: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.326 - error: iqontrol.0 (133850) ERROR updating object: Popup.ButtonDestinationStates: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.328 - error: iqontrol.0 (133850) ERROR updating object: Popup.ButtonCloses: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.329 - error: iqontrol.0 (133850) ERROR updating object: Popup.ButtonClears: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.330 - error: iqontrol.0 (133850) ERROR updating object: Popup.BUTTON_CLICKED: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.331 - error: iqontrol.0 (133850) ERROR updating object: Popup.CLEAR: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.815 - error: iqontrol.0 (133850) ERROR updating object: Lists.Lichter.TOTAL: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.816 - error: iqontrol.0 (133850) ERROR updating object: Lists.Lichter.TOTAL_LIST: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.816 - error: iqontrol.0 (133850) ERROR updating object: Lists.Lichter.TOTAL_LIST_JSON: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.817 - error: iqontrol.0 (133850) ERROR updating object: Lists.Lichter.An: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.818 - error: iqontrol.0 (133850) ERROR updating object: Lists.Lichter.An_LIST: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-14 13:44:49.818 - error: iqontrol.0 (133850) ERROR updating object: Lists.Lichter.An_LIST_JSON: Error: Parameter "options" needs to be a real object but type "boolean" has been passed
```

**Comment by sbormann** [comment]
I think these are two different things. I tried to fix both. Please try the actual github-version i uploaded a few minutes ago and provide feedback.

**Comment by vepman** [comment]
> I think these are two different things. I tried to fix both. Please try the actual github-version i uploaded a few minutes ago and provide feedback.

Die aktuelle github-version geht bei mir auch nicht.
Folgende Protokoll-Ausgabe kommt:

`<html>
<body>


host.iobroker | 2023-06-19 07:05:22.720 | warn | Do not restart adapter system.adapter.iqontrol.0 because restart loop detected
-- | -- | -- | --
host.iobroker | 2023-06-19 07:05:22.720 | info | Restart adapter system.adapter.iqontrol.0 because enabled
host.iobroker | 2023-06-19 07:05:22.720 | error | instance system.adapter.iqontrol.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker | 2023-06-19 07:05:22.719 | error | Caught by controller[0]: at Iqontrol.emit (node:domain:489:12)
host.iobroker | 2023-06-19 07:05:22.719 | error | Caught by controller[0]: at Iqontrol.emit (node:events:513:28)
host.iobroker | 2023-06-19 07:05:22.719 | error | Caught by controller[0]: at Iqontrol.onReady (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1779:14)
host.iobroker | 2023-06-19 07:05:22.719 | error | Caught by controller[0]: at Iqontrol.createInfoConnection (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:413:14)
host.iobroker | 2023-06-19 07:05:22.719 | error | Caught by controller[0]: at Iqontrol.createOrUpdateObject (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1673:25)
host.iobroker | 2023-06-19 07:05:22.719 | error | Caught by controller[0]: at Iqontrol.getObjectAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2308:16)
host.iobroker | 2023-06-19 07:05:22.719 | error | Caught by controller[0]: at new Promise (<anonymous>)
host.iobroker | 2023-06-19 07:05:22.719 | error | Caught by controller[0]: at /opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2309:16
host.iobroker | 2023-06-19 07:05:22.719 | error | Caught by controller[0]: at Iqontrol.getObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:3554:23)
host.iobroker | 2023-06-19 07:05:22.719 | error | Caught by controller[0]: at Function.assertObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:301:19)
host.iobroker | 2023-06-19 07:05:22.719 | error | Caught by controller[0]: Error: Parameter "options" needs to be a real object but type "string" has been passed
host.iobroker | 2023-06-19 07:05:22.719 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:


</body>
</html>`

**Comment by Schorsch99** [comment]
Latest github version works for me, instance now starts without any errors. Many thanks! :-)

 Versionen:
Controller: 5.0.5
iqontrol: 2.2.0 from github
Node.js: v18.16.0

**Comment by vepman** [comment]
@sborman
Sorry, geht immer noch nicht.
Hier das Logdazu:

`<html>
<body>


host.iobroker | 2023-06-19 21:56:36.930 | error | Caught by controller[1]: at Iqontrol.emit (node:events:513:28)
-- | -- | -- | --
host.iobroker | 2023-06-19 21:56:36.929 | error | Caught by controller[1]: at Iqontrol.onReady (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1779:14)
host.iobroker | 2023-06-19 21:56:36.929 | error | Caught by controller[1]: at Iqontrol.createInfoConnection (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:413:14)
host.iobroker | 2023-06-19 21:56:36.929 | error | Caught by controller[1]: at Iqontrol.createOrUpdateObject (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1673:25)
host.iobroker | 2023-06-19 21:56:36.929 | error | Caught by controller[1]: at Iqontrol.getObjectAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2308:16)
host.iobroker | 2023-06-19 21:56:36.929 | error | Caught by controller[1]: at new Promise (<anonymous>)
host.iobroker | 2023-06-19 21:56:36.929 | error | Caught by controller[1]: at /opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2309:16
host.iobroker | 2023-06-19 21:56:36.929 | error | Caught by controller[1]: at Iqontrol.getObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:3554:23)
host.iobroker | 2023-06-19 21:56:36.929 | error | Caught by controller[1]: at Function.assertObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:301:19)
host.iobroker | 2023-06-19 21:56:36.929 | error | Caught by controller[1]: Error: Parameter "options" needs to be a real object but type "string" has been passed
host.iobroker | 2023-06-19 21:56:36.929 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
iqontrol.0 | 2023-06-19 21:56:36.318 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
iqontrol.0 | 2023-06-19 21:56:36.317 | info | terminating
iqontrol.0 | 2023-06-19 21:56:36.316 | info | cleaned everything up...
iqontrol.0 | 2023-06-19 21:56:36.316 | info | Stop trigger intervals...
iqontrol.0 | 2023-06-19 21:56:36.281 | error | Parameter "options" needs to be a real object but type "string" has been passed
iqontrol.0 | 2023-06-19 21:56:36.281 | error | Error: Parameter "options" needs to be a real object but type "string" has been passed at Function.assertObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:301:19) at Iqontrol.getObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:3554:23) at /opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2309:16 at new Promise (<anonymous>) at Iqontrol.getObjectAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2308:16) at Iqontrol.createOrUpdateObject (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1673:25) at Iqontrol.createInfoConnection (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:413:14) at Iqontrol.onReady (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1779:14) at Iqontrol.emit (node:events:513:28) at Iqontrol.emit (node:domain:489:12)
iqontrol.0 | 2023-06-19 21:56:36.024 | error | unhandled promise rejection: Parameter "options" needs to be a real object but type "string" has been passed
iqontrol.0 | 2023-06-19 21:56:36.024 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
iqontrol.0 | 2023-06-19 21:56:35.994 | info | starting. Version 2.2.0 in /opt/iobroker/node_modules/iobroker.iqontrol, node: v18.16.0, js-controller: 5.0.5


</body>
</html>`

**Comment by OstfrieseUnterwegs** [comment]
Ich habe bei der neuesten Git-Version keine Probleme mehr.

**Comment by ihavenonick** [comment]
die neuste Version ohne Angabe dessen ist immer recht eindeutig ;)
Ich habe eben die 5.0.8 geladen und die hat das pPoblem immer noch, was wohl seit mindestens Version 5.0.2 besteht

**Comment by vepman** [comment]
> die neuste Version ohne Angabe dessen ist immer recht eindeutig ;) Ich habe eben die 5.0.8 geladen und die hat das pPoblem immer noch, was wohl seit mindestens Version 5.0.2 besteht

Leider bei mir auch.

**Comment by foxriver76** [comment]
Neuste Version meint GitHub Version von iqontrol @sbormann kannst du evtl eine neue latest version mit den fixes machen?

**Comment by ihavenonick** [comment]
Danke, die läuft.
Ist eben in ein paar Tagen blöd, wenn da steht "neuste Version", ohne Bezug zu irgendwas ;)

**Comment by sbormann** [comment]
Hi, die neue Version mit den Fixes sollte in ein paar Minuten in den latest sein. VG

**Comment by vepman** [comment]
Rückmeldung:
Iqontrol v2.3.0 in Verbindung mit js-controller v5.0.8
läuft bei mir jetzt ohne Probleme. 👍
